// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: car.proto

package com.github.artemdvn.domain;

public final class CarOuterClass {
  private CarOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string model = 1;</code>
     */
    java.lang.String getModel();
    /**
     * <code>string model = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>int32 power = 2;</code>
     */
    int getPower();

    /**
     * <code>.protobuf.Car.EngineType engineType = 3;</code>
     */
    int getEngineTypeValue();
    /**
     * <code>.protobuf.Car.EngineType engineType = 3;</code>
     */
    com.github.artemdvn.domain.CarOuterClass.Car.EngineType getEngineType();

    /**
     * <code>bool used = 4;</code>
     */
    boolean getUsed();

    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption> 
        getOptionsList();
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    com.github.artemdvn.domain.CarOuterClass.CarOption getOptions(int index);
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    int getOptionsCount();
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    java.util.List<? extends com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder> 
        getOptionsOrBuilderList();
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder getOptionsOrBuilder(
        int index);

    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */
    int getMileageCount();
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */
    boolean containsMileage(
        java.lang.String key);
    /**
     * Use {@link #getMileageMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Double>
    getMileage();
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.Double>
    getMileageMap();
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    double getMileageOrDefault(
        java.lang.String key,
        double defaultValue);
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    double getMileageOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code protobuf.Car}
   */
  public  static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      model_ = "";
      engineType_ = 0;
      options_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 16: {

              power_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              engineType_ = rawValue;
              break;
            }
            case 32: {

              used_ = input.readBool();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                options_ = new java.util.ArrayList<com.github.artemdvn.domain.CarOuterClass.CarOption>();
                mutable_bitField0_ |= 0x00000010;
              }
              options_.add(
                  input.readMessage(com.github.artemdvn.domain.CarOuterClass.CarOption.parser(), extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) != 0)) {
                mileage_ = com.google.protobuf.MapField.newMapField(
                    MileageDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
              mileage__ = input.readMessage(
                  MileageDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mileage_.getMutableMap().put(
                  mileage__.getKey(), mileage__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetMileage();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.artemdvn.domain.CarOuterClass.Car.class, com.github.artemdvn.domain.CarOuterClass.Car.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.Car.EngineType}
     */
    public enum EngineType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GASOLINE = 0;</code>
       */
      GASOLINE(0),
      /**
       * <code>DIESEL = 1;</code>
       */
      DIESEL(1),
      /**
       * <code>HYBRID = 2;</code>
       */
      HYBRID(2),
      /**
       * <code>ELECTRIC = 3;</code>
       */
      ELECTRIC(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GASOLINE = 0;</code>
       */
      public static final int GASOLINE_VALUE = 0;
      /**
       * <code>DIESEL = 1;</code>
       */
      public static final int DIESEL_VALUE = 1;
      /**
       * <code>HYBRID = 2;</code>
       */
      public static final int HYBRID_VALUE = 2;
      /**
       * <code>ELECTRIC = 3;</code>
       */
      public static final int ELECTRIC_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EngineType valueOf(int value) {
        return forNumber(value);
      }

      public static EngineType forNumber(int value) {
        switch (value) {
          case 0: return GASOLINE;
          case 1: return DIESEL;
          case 2: return HYBRID;
          case 3: return ELECTRIC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EngineType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EngineType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EngineType>() {
              public EngineType findValueByNumber(int number) {
                return EngineType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.artemdvn.domain.CarOuterClass.Car.getDescriptor().getEnumTypes().get(0);
      }

      private static final EngineType[] VALUES = values();

      public static EngineType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EngineType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.Car.EngineType)
    }

    private int bitField0_;
    public static final int MODEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object model_;
    /**
     * <code>string model = 1;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>string model = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POWER_FIELD_NUMBER = 2;
    private int power_;
    /**
     * <code>int32 power = 2;</code>
     */
    public int getPower() {
      return power_;
    }

    public static final int ENGINETYPE_FIELD_NUMBER = 3;
    private int engineType_;
    /**
     * <code>.protobuf.Car.EngineType engineType = 3;</code>
     */
    public int getEngineTypeValue() {
      return engineType_;
    }
    /**
     * <code>.protobuf.Car.EngineType engineType = 3;</code>
     */
    public com.github.artemdvn.domain.CarOuterClass.Car.EngineType getEngineType() {
      @SuppressWarnings("deprecation")
      com.github.artemdvn.domain.CarOuterClass.Car.EngineType result = com.github.artemdvn.domain.CarOuterClass.Car.EngineType.valueOf(engineType_);
      return result == null ? com.github.artemdvn.domain.CarOuterClass.Car.EngineType.UNRECOGNIZED : result;
    }

    public static final int USED_FIELD_NUMBER = 4;
    private boolean used_;
    /**
     * <code>bool used = 4;</code>
     */
    public boolean getUsed() {
      return used_;
    }

    public static final int OPTIONS_FIELD_NUMBER = 5;
    private java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption> options_;
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    public java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption> getOptionsList() {
      return options_;
    }
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    public java.util.List<? extends com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder> 
        getOptionsOrBuilderList() {
      return options_;
    }
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    public int getOptionsCount() {
      return options_.size();
    }
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    public com.github.artemdvn.domain.CarOuterClass.CarOption getOptions(int index) {
      return options_.get(index);
    }
    /**
     * <code>repeated .protobuf.CarOption options = 5;</code>
     */
    public com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder getOptionsOrBuilder(
        int index) {
      return options_.get(index);
    }

    public static final int MILEAGE_FIELD_NUMBER = 6;
    private static final class MileageDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Double> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Double>newDefaultInstance(
                  com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_MileageEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.DOUBLE,
                  0D);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Double> mileage_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
    internalGetMileage() {
      if (mileage_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MileageDefaultEntryHolder.defaultEntry);
      }
      return mileage_;
    }

    public int getMileageCount() {
      return internalGetMileage().getMap().size();
    }
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    public boolean containsMileage(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMileage().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMileageMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Double> getMileage() {
      return getMileageMap();
    }
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Double> getMileageMap() {
      return internalGetMileage().getMap();
    }
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    public double getMileageOrDefault(
        java.lang.String key,
        double defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMileage().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, double&gt; mileage = 6;</code>
     */

    public double getMileageOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Double> map =
          internalGetMileage().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
      }
      if (power_ != 0) {
        output.writeInt32(2, power_);
      }
      if (engineType_ != com.github.artemdvn.domain.CarOuterClass.Car.EngineType.GASOLINE.getNumber()) {
        output.writeEnum(3, engineType_);
      }
      if (used_ != false) {
        output.writeBool(4, used_);
      }
      for (int i = 0; i < options_.size(); i++) {
        output.writeMessage(5, options_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMileage(),
          MileageDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
      }
      if (power_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, power_);
      }
      if (engineType_ != com.github.artemdvn.domain.CarOuterClass.Car.EngineType.GASOLINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, engineType_);
      }
      if (used_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, used_);
      }
      for (int i = 0; i < options_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, options_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
           : internalGetMileage().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
        mileage__ = MileageDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, mileage__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.artemdvn.domain.CarOuterClass.Car)) {
        return super.equals(obj);
      }
      com.github.artemdvn.domain.CarOuterClass.Car other = (com.github.artemdvn.domain.CarOuterClass.Car) obj;

      if (!getModel()
          .equals(other.getModel())) return false;
      if (getPower()
          != other.getPower()) return false;
      if (engineType_ != other.engineType_) return false;
      if (getUsed()
          != other.getUsed()) return false;
      if (!getOptionsList()
          .equals(other.getOptionsList())) return false;
      if (!internalGetMileage().equals(
          other.internalGetMileage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + POWER_FIELD_NUMBER;
      hash = (53 * hash) + getPower();
      hash = (37 * hash) + ENGINETYPE_FIELD_NUMBER;
      hash = (53 * hash) + engineType_;
      hash = (37 * hash) + USED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUsed());
      if (getOptionsCount() > 0) {
        hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getOptionsList().hashCode();
      }
      if (!internalGetMileage().getMap().isEmpty()) {
        hash = (37 * hash) + MILEAGE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMileage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.artemdvn.domain.CarOuterClass.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Car)
        com.github.artemdvn.domain.CarOuterClass.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMileage();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableMileage();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.artemdvn.domain.CarOuterClass.Car.class, com.github.artemdvn.domain.CarOuterClass.Car.Builder.class);
      }

      // Construct using com.github.artemdvn.domain.CarOuterClass.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOptionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        model_ = "";

        power_ = 0;

        engineType_ = 0;

        used_ = false;

        if (optionsBuilder_ == null) {
          options_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          optionsBuilder_.clear();
        }
        internalGetMutableMileage().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_Car_descriptor;
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.Car getDefaultInstanceForType() {
        return com.github.artemdvn.domain.CarOuterClass.Car.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.Car build() {
        com.github.artemdvn.domain.CarOuterClass.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.Car buildPartial() {
        com.github.artemdvn.domain.CarOuterClass.Car result = new com.github.artemdvn.domain.CarOuterClass.Car(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.model_ = model_;
        result.power_ = power_;
        result.engineType_ = engineType_;
        result.used_ = used_;
        if (optionsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            options_ = java.util.Collections.unmodifiableList(options_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.options_ = options_;
        } else {
          result.options_ = optionsBuilder_.build();
        }
        result.mileage_ = internalGetMileage();
        result.mileage_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.artemdvn.domain.CarOuterClass.Car) {
          return mergeFrom((com.github.artemdvn.domain.CarOuterClass.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.artemdvn.domain.CarOuterClass.Car other) {
        if (other == com.github.artemdvn.domain.CarOuterClass.Car.getDefaultInstance()) return this;
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (other.getPower() != 0) {
          setPower(other.getPower());
        }
        if (other.engineType_ != 0) {
          setEngineTypeValue(other.getEngineTypeValue());
        }
        if (other.getUsed() != false) {
          setUsed(other.getUsed());
        }
        if (optionsBuilder_ == null) {
          if (!other.options_.isEmpty()) {
            if (options_.isEmpty()) {
              options_ = other.options_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureOptionsIsMutable();
              options_.addAll(other.options_);
            }
            onChanged();
          }
        } else {
          if (!other.options_.isEmpty()) {
            if (optionsBuilder_.isEmpty()) {
              optionsBuilder_.dispose();
              optionsBuilder_ = null;
              options_ = other.options_;
              bitField0_ = (bitField0_ & ~0x00000010);
              optionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOptionsFieldBuilder() : null;
            } else {
              optionsBuilder_.addAllMessages(other.options_);
            }
          }
        }
        internalGetMutableMileage().mergeFrom(
            other.internalGetMileage());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.artemdvn.domain.CarOuterClass.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.artemdvn.domain.CarOuterClass.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object model_ = "";
      /**
       * <code>string model = 1;</code>
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model = 1;</code>
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model = 1;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>string model = 1;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private int power_ ;
      /**
       * <code>int32 power = 2;</code>
       */
      public int getPower() {
        return power_;
      }
      /**
       * <code>int32 power = 2;</code>
       */
      public Builder setPower(int value) {
        
        power_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 power = 2;</code>
       */
      public Builder clearPower() {
        
        power_ = 0;
        onChanged();
        return this;
      }

      private int engineType_ = 0;
      /**
       * <code>.protobuf.Car.EngineType engineType = 3;</code>
       */
      public int getEngineTypeValue() {
        return engineType_;
      }
      /**
       * <code>.protobuf.Car.EngineType engineType = 3;</code>
       */
      public Builder setEngineTypeValue(int value) {
        engineType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Car.EngineType engineType = 3;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.Car.EngineType getEngineType() {
        @SuppressWarnings("deprecation")
        com.github.artemdvn.domain.CarOuterClass.Car.EngineType result = com.github.artemdvn.domain.CarOuterClass.Car.EngineType.valueOf(engineType_);
        return result == null ? com.github.artemdvn.domain.CarOuterClass.Car.EngineType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.Car.EngineType engineType = 3;</code>
       */
      public Builder setEngineType(com.github.artemdvn.domain.CarOuterClass.Car.EngineType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        engineType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.Car.EngineType engineType = 3;</code>
       */
      public Builder clearEngineType() {
        
        engineType_ = 0;
        onChanged();
        return this;
      }

      private boolean used_ ;
      /**
       * <code>bool used = 4;</code>
       */
      public boolean getUsed() {
        return used_;
      }
      /**
       * <code>bool used = 4;</code>
       */
      public Builder setUsed(boolean value) {
        
        used_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool used = 4;</code>
       */
      public Builder clearUsed() {
        
        used_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption> options_ =
        java.util.Collections.emptyList();
      private void ensureOptionsIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          options_ = new java.util.ArrayList<com.github.artemdvn.domain.CarOuterClass.CarOption>(options_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.artemdvn.domain.CarOuterClass.CarOption, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder, com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder> optionsBuilder_;

      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption> getOptionsList() {
        if (optionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(options_);
        } else {
          return optionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public int getOptionsCount() {
        if (optionsBuilder_ == null) {
          return options_.size();
        } else {
          return optionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.CarOption getOptions(int index) {
        if (optionsBuilder_ == null) {
          return options_.get(index);
        } else {
          return optionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder setOptions(
          int index, com.github.artemdvn.domain.CarOuterClass.CarOption value) {
        if (optionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionsIsMutable();
          options_.set(index, value);
          onChanged();
        } else {
          optionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder setOptions(
          int index, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder builderForValue) {
        if (optionsBuilder_ == null) {
          ensureOptionsIsMutable();
          options_.set(index, builderForValue.build());
          onChanged();
        } else {
          optionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder addOptions(com.github.artemdvn.domain.CarOuterClass.CarOption value) {
        if (optionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionsIsMutable();
          options_.add(value);
          onChanged();
        } else {
          optionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder addOptions(
          int index, com.github.artemdvn.domain.CarOuterClass.CarOption value) {
        if (optionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionsIsMutable();
          options_.add(index, value);
          onChanged();
        } else {
          optionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder addOptions(
          com.github.artemdvn.domain.CarOuterClass.CarOption.Builder builderForValue) {
        if (optionsBuilder_ == null) {
          ensureOptionsIsMutable();
          options_.add(builderForValue.build());
          onChanged();
        } else {
          optionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder addOptions(
          int index, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder builderForValue) {
        if (optionsBuilder_ == null) {
          ensureOptionsIsMutable();
          options_.add(index, builderForValue.build());
          onChanged();
        } else {
          optionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder addAllOptions(
          java.lang.Iterable<? extends com.github.artemdvn.domain.CarOuterClass.CarOption> values) {
        if (optionsBuilder_ == null) {
          ensureOptionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, options_);
          onChanged();
        } else {
          optionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder clearOptions() {
        if (optionsBuilder_ == null) {
          options_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          optionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public Builder removeOptions(int index) {
        if (optionsBuilder_ == null) {
          ensureOptionsIsMutable();
          options_.remove(index);
          onChanged();
        } else {
          optionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.CarOption.Builder getOptionsBuilder(
          int index) {
        return getOptionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder getOptionsOrBuilder(
          int index) {
        if (optionsBuilder_ == null) {
          return options_.get(index);  } else {
          return optionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public java.util.List<? extends com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder> 
           getOptionsOrBuilderList() {
        if (optionsBuilder_ != null) {
          return optionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(options_);
        }
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.CarOption.Builder addOptionsBuilder() {
        return getOptionsFieldBuilder().addBuilder(
            com.github.artemdvn.domain.CarOuterClass.CarOption.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public com.github.artemdvn.domain.CarOuterClass.CarOption.Builder addOptionsBuilder(
          int index) {
        return getOptionsFieldBuilder().addBuilder(
            index, com.github.artemdvn.domain.CarOuterClass.CarOption.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.CarOption options = 5;</code>
       */
      public java.util.List<com.github.artemdvn.domain.CarOuterClass.CarOption.Builder> 
           getOptionsBuilderList() {
        return getOptionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.github.artemdvn.domain.CarOuterClass.CarOption, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder, com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder> 
          getOptionsFieldBuilder() {
        if (optionsBuilder_ == null) {
          optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.github.artemdvn.domain.CarOuterClass.CarOption, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder, com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder>(
                  options_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          options_ = null;
        }
        return optionsBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> mileage_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMileage() {
        if (mileage_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MileageDefaultEntryHolder.defaultEntry);
        }
        return mileage_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetMutableMileage() {
        onChanged();;
        if (mileage_ == null) {
          mileage_ = com.google.protobuf.MapField.newMapField(
              MileageDefaultEntryHolder.defaultEntry);
        }
        if (!mileage_.isMutable()) {
          mileage_ = mileage_.copy();
        }
        return mileage_;
      }

      public int getMileageCount() {
        return internalGetMileage().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public boolean containsMileage(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMileage().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMileageMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double> getMileage() {
        return getMileageMap();
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Double> getMileageMap() {
        return internalGetMileage().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public double getMileageOrDefault(
          java.lang.String key,
          double defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMileage().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public double getMileageOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetMileage().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMileage() {
        internalGetMutableMileage().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public Builder removeMileage(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMileage().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double>
      getMutableMileage() {
        return internalGetMutableMileage().getMutableMap();
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */
      public Builder putMileage(
          java.lang.String key,
          double value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableMileage().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, double&gt; mileage = 6;</code>
       */

      public Builder putAllMileage(
          java.util.Map<java.lang.String, java.lang.Double> values) {
        internalGetMutableMileage().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.Car)
    }

    // @@protoc_insertion_point(class_scope:protobuf.Car)
    private static final com.github.artemdvn.domain.CarOuterClass.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.artemdvn.domain.CarOuterClass.Car();
    }

    public static com.github.artemdvn.domain.CarOuterClass.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.artemdvn.domain.CarOuterClass.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarOptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.CarOption)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string option = 1;</code>
     */
    java.lang.String getOption();
    /**
     * <code>string option = 1;</code>
     */
    com.google.protobuf.ByteString
        getOptionBytes();

    /**
     * <code>double price = 2;</code>
     */
    double getPrice();
  }
  /**
   * Protobuf type {@code protobuf.CarOption}
   */
  public  static final class CarOption extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.CarOption)
      CarOptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarOption.newBuilder() to construct.
    private CarOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarOption() {
      option_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarOption(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              option_ = s;
              break;
            }
            case 17: {

              price_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_CarOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_CarOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.artemdvn.domain.CarOuterClass.CarOption.class, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder.class);
    }

    public static final int OPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object option_;
    /**
     * <code>string option = 1;</code>
     */
    public java.lang.String getOption() {
      java.lang.Object ref = option_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        option_ = s;
        return s;
      }
    }
    /**
     * <code>string option = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOptionBytes() {
      java.lang.Object ref = option_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        option_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_;
    /**
     * <code>double price = 2;</code>
     */
    public double getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, option_);
      }
      if (price_ != 0D) {
        output.writeDouble(2, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, option_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.artemdvn.domain.CarOuterClass.CarOption)) {
        return super.equals(obj);
      }
      com.github.artemdvn.domain.CarOuterClass.CarOption other = (com.github.artemdvn.domain.CarOuterClass.CarOption) obj;

      if (!getOption()
          .equals(other.getOption())) return false;
      if (java.lang.Double.doubleToLongBits(getPrice())
          != java.lang.Double.doubleToLongBits(
              other.getPrice())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPTION_FIELD_NUMBER;
      hash = (53 * hash) + getOption().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.artemdvn.domain.CarOuterClass.CarOption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.artemdvn.domain.CarOuterClass.CarOption prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.CarOption}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.CarOption)
        com.github.artemdvn.domain.CarOuterClass.CarOptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_CarOption_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_CarOption_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.artemdvn.domain.CarOuterClass.CarOption.class, com.github.artemdvn.domain.CarOuterClass.CarOption.Builder.class);
      }

      // Construct using com.github.artemdvn.domain.CarOuterClass.CarOption.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        option_ = "";

        price_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.artemdvn.domain.CarOuterClass.internal_static_protobuf_CarOption_descriptor;
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.CarOption getDefaultInstanceForType() {
        return com.github.artemdvn.domain.CarOuterClass.CarOption.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.CarOption build() {
        com.github.artemdvn.domain.CarOuterClass.CarOption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.artemdvn.domain.CarOuterClass.CarOption buildPartial() {
        com.github.artemdvn.domain.CarOuterClass.CarOption result = new com.github.artemdvn.domain.CarOuterClass.CarOption(this);
        result.option_ = option_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.artemdvn.domain.CarOuterClass.CarOption) {
          return mergeFrom((com.github.artemdvn.domain.CarOuterClass.CarOption)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.artemdvn.domain.CarOuterClass.CarOption other) {
        if (other == com.github.artemdvn.domain.CarOuterClass.CarOption.getDefaultInstance()) return this;
        if (!other.getOption().isEmpty()) {
          option_ = other.option_;
          onChanged();
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.artemdvn.domain.CarOuterClass.CarOption parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.artemdvn.domain.CarOuterClass.CarOption) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object option_ = "";
      /**
       * <code>string option = 1;</code>
       */
      public java.lang.String getOption() {
        java.lang.Object ref = option_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          option_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string option = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOptionBytes() {
        java.lang.Object ref = option_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          option_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string option = 1;</code>
       */
      public Builder setOption(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        option_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string option = 1;</code>
       */
      public Builder clearOption() {
        
        option_ = getDefaultInstance().getOption();
        onChanged();
        return this;
      }
      /**
       * <code>string option = 1;</code>
       */
      public Builder setOptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        option_ = value;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 2;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 2;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 2;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.CarOption)
    }

    // @@protoc_insertion_point(class_scope:protobuf.CarOption)
    private static final com.github.artemdvn.domain.CarOuterClass.CarOption DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.artemdvn.domain.CarOuterClass.CarOption();
    }

    public static com.github.artemdvn.domain.CarOuterClass.CarOption getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarOption>
        PARSER = new com.google.protobuf.AbstractParser<CarOption>() {
      @java.lang.Override
      public CarOption parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarOption(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarOption> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarOption> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.artemdvn.domain.CarOuterClass.CarOption getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Car_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Car_MileageEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_Car_MileageEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_CarOption_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_CarOption_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcar.proto\022\010protobuf\"\244\002\n\003Car\022\r\n\005model\030\001" +
      " \001(\t\022\r\n\005power\030\002 \001(\005\022,\n\nengineType\030\003 \001(\0162" +
      "\030.protobuf.Car.EngineType\022\014\n\004used\030\004 \001(\010\022" +
      "$\n\007options\030\005 \003(\0132\023.protobuf.CarOption\022+\n" +
      "\007mileage\030\006 \003(\0132\032.protobuf.Car.MileageEnt" +
      "ry\032.\n\014MileageEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\001:\0028\001\"@\n\nEngineType\022\014\n\010GASOLINE\020\000\022\n" +
      "\n\006DIESEL\020\001\022\n\n\006HYBRID\020\002\022\014\n\010ELECTRIC\020\003\"*\n\t" +
      "CarOption\022\016\n\006option\030\001 \001(\t\022\r\n\005price\030\002 \001(\001" +
      "B\034\n\032com.github.artemdvn.domainb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Car_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Car_descriptor,
        new java.lang.String[] { "Model", "Power", "EngineType", "Used", "Options", "Mileage", });
    internal_static_protobuf_Car_MileageEntry_descriptor =
      internal_static_protobuf_Car_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Car_MileageEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_Car_MileageEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protobuf_CarOption_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_CarOption_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_CarOption_descriptor,
        new java.lang.String[] { "Option", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
